[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = false
offline = true
solc_version = "0.8.30"
optimizer = false
evm_version = "cancun"
remappings = []

ignored_error_codes = [3628, 9302, "license", "unused-param", "unused-var", "func-mutability"]

ffi = false

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.sepolia]
chain_id = 11155111
eth_rpc_url = "${SEPOLIA_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[profile.baseSepolia]
chain_id = 84532
eth_rpc_url = "${BASE_SEPOLIA_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[profile.polygonAmoy]
chain_id = 80002
eth_rpc_url = "${POLYGON_AMOY_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
polygonAmoy = "${POLYGON_AMOY_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${BASESCAN_API_KEY}" }
polygonAmoy = { key = "${POLYGONSCAN_API_KEY}" }

[fmt]
line_length = 80

[fuzz]
runs = 10

[invariant]
runs = 10
depth = 15

