[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
remappings = []

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.sepolia]
chain_id = 11155111
eth_rpc_url = "${SEPOLIA_RPC_URL}"
private_key = "${PRIVATE_KEY}"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

